num_humans: 4 # Number should match the number of individual human configs from below

#scenario 0 normal ORCA humans going around
#scenario 1 - ORCA, Inhus and CoHAN
human_1:
  loop_path: False
  planner_name: 'gbl_planner/make_plan'
  scenarios:
    selected_id: 1 # ID to select from the goal sequence below. Starts with 0
    goals: [ # Sequence provided by scenerio
      [[4.5, -5.6], [11.0, 22.1]],
      [[7.75, 5.0], [8.6, 22.9]],
      [[8.5, 2.31], [8.5, -5.0]]
    ]

human_2:
  loop_path: False
  planner_name: 'gbl_planner/make_plan'
  scenarios:
    selected_id: 0 # same for 1 as well
    goals: [ # Sequence provided by scenerio
      [[1.0, 2.4], [11.0, 19.6]], #[5.45, 11.4]],
      [[2.0, 1.0]],
      [[8.5, -5.0], [8.5, 2.31]]
    ]

human_3:
  loop_path: False
  planner_name: 'gbl_planner/make_plan'
  scenarios:
    selected_id: 0
    goals: [ # Sequence provided by scenerio
      [[2.75, -5.2], [8.64, 10.9]],
      [[2.0, 1.0]],
      [[10.0, 15.0], [10.0, 2.00]]
    ]

human_4:
  loop_path: False
  planner_name: 'gbl_planner/make_plan'
  scenarios:
    selected_id: 0
    goals: [ # Sequence provided by scenerio
      [[10.0, -0.4], [7.94, 19.4]],
      [[2.0, 1.0]],
      [[4.0, 1.4], [4.0, -1.4]]
    ]

human_5:
  loop_path: False
  planner_name: 'gbl_planner/make_plan'
  scenarios:
    selected_id: 2
    goals: [ # Sequence provided by scenerio
      [[1.0, 1.0], [2.0, 2.0]],
      [[2.0, 1.0]],
      [[4.0, -1.4], [4.0, 1.4]]
    ]

human_6:
  loop_path: False
  planner_name: 'gbl_planner/make_plan'
  scenarios:
    selected_id: 2
    goals: [ # Sequence provided by scenerio
      [[1.0, 1.0], [2.0, 2.0]],
      [[2.0, 1.0]],
      [[5.1, 21.6], [7.2, 10.2]]
    ]

human_7:
  loop_path: False
  planner_name: 'gbl_planner/make_plan'
  scenarios:
    selected_id: 2
    goals: [ # Sequence provided by scenerio
      [[1.0, 1.0], [2.0, 2.0]],
      [[2.0, 1.0]],
      [[7.2, 10.1], [5.1, 21.1]]
    ]

human_8:
  loop_path: False
  planner_name: 'gbl_planner/make_plan'
  scenarios:
    selected_id: 2
    goals: [ # Sequence provided by scenerio
      [[1.0, 1.0], [2.0, 2.0]],
      [[2.0, 1.0]],
      [[6.1, 1.6], [6.1, 14.1]]
    ]

human_9:
  loop_path: False
  planner_name: 'gbl_planner/make_plan'
  scenarios:
    selected_id: 2
    goals: [ # Sequence provided by scenerio
      [[1.0, 1.0], [2.0, 2.0]],
      [[2.0, 1.0]],
      [[6.0, 14.0], [6.0, 1.5]]
    ]

human_10:
  loop_path: False
  planner_name: 'gbl_planner/make_plan'
  scenarios:
    selected_id: 2
    goals: [ # Sequence provided by scenerio
      [[1.0, 1.0], [2.0, 2.0]],
      [[2.0, 1.0]],
      [[2.1, 2.1], [2.1, 14.1]]
    ]
