num_humans: 7 # Number should match the number of individual human configs from below

#scenario 0 normal ORCA humans going around
#scenario 1 - ORCA, Inhus and CoHAN
human_1:
  loop_path: True
  planner_name: 'gbl_planner/make_plan'
  scenarios:
    selected_id: 10                                                  #9 - normal doorway crossing #8 - diamond #7 - squad #6- free space,  5 - train queue, 4 - wide corridor scenario, 3 - for obstacle avoidance test and agent avoidance test # ID to select from the goal sequence below. Starts with 0
    goals: [                                                         # Sequence provided by scenerio
      [[8.46, -5.79], [8.46, 2.0]], #[[4.5, -5.6], [11.0, 22.1]],
      [[7.75, 5.0], [8.6, 22.9]],
      [[8.5, 2.31], [8.5, -5.0]],
      [[10.0, 15.6], [1.28, 15.6]],
      [[10.2, 0.9], [10.2, 14.0]],
      [[10.2, 17.6], [10.2, 1.84]],
      [[10.5, 17.2], [1.0, 17.2]],
      [[9.5, 17.2], [1.0, 17.2]],
      [[8.0, 13.4], [4.0, 17.4]],
      [[3.45, 13.6], [5.15, 22.2]],
      [[8.0, 22.0], [6.4, 14.8]]        
    ]

human_2:
  loop_path: True
  planner_name: 'gbl_planner/make_plan'
  scenarios:
    selected_id: 10 #9 - normal doorway crossing #8 - diamond #7 - squad #6 - free space # 5 - train queue, 4 - wide corridor scenario, 3 - for obstacle avoidance test and agent avoidance test # same for 1 as well
    goals: [ # Sequence provided by scenerio
      [[8.46, 2.0], [8.46, -5.79]], # [[1.0, 2.4], [11.0, 19.6]], #[5.45, 11.4]],
      [[2.0, 1.0]],
      [[8.5, -5.0], [8.5, 2.31]],
      [[1.28, 15.6], [10.0, 15.6]],
      [[10.2, 14.0], [10.2, 0.9]],
      [[10.2, 16.4], [10.2, 0.6]],
      [[10.5, 16.5], [1.0, 16.5]],
      [[10.5, 16.5], [2.0, 16.5]],
      [[4.0, 17.4], [8.0, 13.4]],
      [[5.0, 13.6], [6.5, 22.2]],
      [[9.0, 22.0], [4.2, 14.8]]             
    ]

human_3:
  loop_path: True
  planner_name: 'gbl_planner/make_plan'
  scenarios:
    selected_id: 8 #7 - normal doorway crossing #6 - diamond #5 -squad #4 - free space #3 - train queue #1 # 0 - narrow corridor, 1 - wide corridor
    goals: [ # Sequence provided by scenerio
      [[0.75, 3.5], [0.75, 13.5]], # [[2.75, -5.2], [8.64, 10.9]],
      [[10.2, 14.5], [10.2, 1.33]],
      [[10.0, 15.0], [10.0, 2.00]],


      [[10.2, 15.0], [10.2, -0.6]],
      [[10.5, 15.5], [1.0, 15.5]],
      [[10.5, 15.5], [2.0, 15.5]],
      [[8.0, 17.4], [4.0, 13.4]],
      [[6.0, 13.6], [7.75, 21.4]],
      [[10.5, 15.7], [1.0, 15.7]]         
    ]

human_4:
  loop_path: True
  planner_name: 'gbl_planner/make_plan'
  scenarios:
    selected_id: 8 #7 - normal doorway crossing #6 - diamond #5 -squad #4 - free space #3 - train queue #1 #0 - narrow corridor, 1 - wide corridor
    goals: [ # Sequence provided by scenerio
      [[0.75, 13.5], [0.75, 3.5]],  # [[10.0, -0.4], [7.94, 19.4]],
      [[10.2, 1.33], [10.2, 14.5]],
      [[4.0, 1.4], [4.0, -1.4]],


      [[10.2, 14.0], [10.2, -1.8]],
      [[10.5, 14.5], [1.0, 14.5]],
      [[9.5, 14.5], [1.0, 14.5]],
      [[4.0, 13.4], [8.0, 17.4]],
      [[7.0, 13.6], [8.25, 19.8]],
      [[10.5, 16.5], [1.0, 16.5]]           
    ]

human_5:
  loop_path: True
  planner_name: 'gbl_planner/make_plan'
  scenarios:
    selected_id: 5 #3
    goals: [ # Sequence provided by scenerio
      [[10.2, 14.5], [10.2, 1.33]],      # [[1.0, 1.0], [2.0, 2.0]],
      [[2.0, 1.0]],
      [[4.0, -1.4], [4.0, 1.4]],

      [[10.2, 13.0], [10.2, 0.9]],
      [[10.2, 0.9], [10.2, 14.0]],
      [[10.5, 15.0], [1.0, 15.0]] 
    ]

human_6:
  loop_path: True
  planner_name: 'gbl_planner/make_plan'
  scenarios:
    selected_id: 4 #2
    goals: [ # Sequence provided by scenerio
      [[1.0, 1.0], [2.0, 2.0]],
      [[2.0, 1.0]],
      [[5.1, 21.6], [7.2, 10.2]],

      [[10.2, 0.9], [10.2, 14.0]],
      [[10.5, 14.3], [1.0, 14.3]] 
    ]

human_7:
  loop_path: True
  planner_name: 'gbl_planner/make_plan'
  scenarios:
    selected_id: 3 #2
    goals: [ # Sequence provided by scenerio
      [[1.0, 1.0], [2.0, 2.0]],
      [[2.0, 1.0]],
      [[7.2, 10.1], [5.1, 21.1]],
      [[10.5, 13.5], [1.0, 13.5]] 
    ]

human_8:
  loop_path: False
  planner_name: 'gbl_planner/make_plan'
  scenarios:
    selected_id: 2
    goals: [ # Sequence provided by scenerio
      [[1.0, 1.0], [2.0, 2.0]],
      [[2.0, 1.0]],
      [[6.1, 1.6], [6.1, 14.1]]
    ]

human_9:
  loop_path: False
  planner_name: 'gbl_planner/make_plan'
  scenarios:
    selected_id: 2
    goals: [ # Sequence provided by scenerio
      [[1.0, 1.0], [2.0, 2.0]],
      [[2.0, 1.0]],
      [[6.0, 14.0], [6.0, 1.5]]
    ]

human_10:
  loop_path: False
  planner_name: 'gbl_planner/make_plan'
  scenarios:
    selected_id: 2
    goals: [ # Sequence provided by scenerio
      [[1.0, 1.0], [2.0, 2.0]],
      [[2.0, 1.0]],
      [[2.1, 2.1], [2.1, 14.1]]
    ]
