num_humans: 3 # Number should match the number of individual human configs from below

human_1:
  loop_path: True
  planner_name: 'gbl_planner/make_plan'
  scenarios:
    initial_scene_id: 2 # ID to select from the goal sequence below. Starts with 0 which is considered as initial pose.
    goals: [ # Sequence provided by scenerio
      [[1.0, 1.0], [2.0, 2.0]],
      [[2.0, 1.0]],
      [[8.5, 2.31], [8.5, -5.0]]
    ]

human_2:
  loop_path: True
  planner_name: 'gbl_planner/make_plan'
  scenarios:
    initial_scene_id: 2
    goals: [ # Sequence provided by scenerio
      [[1.0, 1.0], [2.0, 2.0]],
      [[2.0, 1.0]],
      [[8.5, -5.0], [8.5, 2.31]]
    ]

human_3:
  loop_path: True
  planner_name: 'gbl_planner/make_plan'
  scenarios:
    initial_scene_id: 2
    goals: [ # Sequence provided by scenerio
      [[1.0, 1.0], [2.0, 2.0]],
      [[2.0, 1.0]],
      [[10.0, 15.0], [10.0, 2.00]]
    ]