global_costmap:
  global_frame: map
  robot_base_frame: base_footprint
  update_frequency: 20.0
  publish_frequency: 20.0
  width: 15.0
  height: 30.0
  origin_x: -2.0
  origin_y: -8.0
  robot_radius: 0.3
  # footprint: [[-0.325, -0.325], [-0.325, 0.325], [0.325, 0.325], [0.46, 0.0], [0.325, -0.325]]


  plugins:
  - {name: static_layer, type: "costmap_2d::StaticLayer"}
  - {name: obstacle_layer, type: "costmap_2d::ObstacleLayer"}
  - {name: inflater_layer, type: "costmap_2d::InflationLayer"}
